author: Lupus and Ludo0777
database: false
description: Control what guests can do on your server!
main: us.lupusbukkit.GuestGuard.GuestGuard
name: 'GuestGuard'
startup: postworld
version: '0.5'
permissions:  
  guestguard.build:
    default: op
    description: Allow players to build
  guestguard.chat:
    default: op
    description: Allow players to chat
  guestguard.drop:
    default: op
    description: Allow players to drop items
  guestguard.pickup:
    default: op
    description: Allow players to pickup items